/*
    WEEK 02 - PROGRAM 03: GUESSING OF RANDOM NUMBERS
    Create a program that allows the system to generate a random number between [1, 200], 
    and the user has the required attempts to enter numbers until he can guess the number generated by the system.
    - If the user guesses correctly, the system should allow him to continue the game to guess new random numbers;
    - Otherwise, the system should indicate whether the number entered by the user is greater or less 
      than the random number generated by the system.

    Definition of variables:
        - n: random number generated by system
        - guess: number input by the user to try guess random number n
        - play: option to continuing play or not [Y|N]
*/

#include <iostream>
#include <cmath>
#include <ctime>
#include <cstdlib>
using namespace std;

int main(){
    // definition of variables
    int n, guess;
    char play;    

    // seed random number using currently time
    srand(static_cast<unsigned int>(time(0)));

    // cycle to control continuing of game
    do{
        n = 1 + rand() % 200;   // generation of random number
        
        // cycle to control flow of guessing
        do{
            cout<< "Guess the number: ";
            cin>> guess;

            if(guess < n){
                cout<< "\nToo low... please try again"<<endl;
            }                
            else if(guess > n){
                cout<< "\nToo high... please try again"<<endl;
            }
        }while(guess != n);
        
        cout<< "You guess the number! n = "<< n<< endl;
        cout<< "Want play again [Y|N]?"<< endl;
        cin>>play;

    }while(play == 'y' || play == 'Y');

    cout<< "Game is finished!"<< endl;

    return 0;
}
